### PR TITLE
Fix for positive floating numbers with sign and no numbers preceding point

### PR DESCRIPTION
**Pull request by Failproofshark**
Hello,

I recently ran into a problem concerning floating point numbers in the form "+.231". It handles other numbers with a leading "+" sign just fine but the example above would produce an invalid integer error when it finally calls `cl:parse-integer`. 

In response, I have added a few test cases with numbers having a "+" sign in them as well as the erroneous case. I have also provided a fix for said problem.

Thanks.

### CODE REVIEW

**Comment by libre-man** [comment]
Hi I'm also experiencing this problem, are there any issues with this PR?

**Comment by luismbo** [comment]
Pushed c7ca3f9 with some minor tweaks. @sionescu can you do the release dance?

**Comment by luismbo** [comment]
Thanks @Failproofshark and @libre-man!

**Comment by sionescu** [comment]
Ok, I'll do the release tonight.

**Comment by sionescu** [comment]
Done.

**Pull request closed without merging**
